djangoProject1/animation/urls.py
from .import views
from django.urls import path
urlpatterns=[path("",views.index,name="index")]

djangoProject1/djangoProject1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scroll/',include('scroll.urls')),
    path('infiniteScroll',include('infiniteScroll.urls')),
    path('animation',include('animation.urls')),
    path('flight/',include('flight.urls')),
    path('singlePageApplication/',include('singlePageApplication.urls')),
    path('singlePage1/',include('singlePage1.urls'))

]

djangoProject1/flight/urls.py
from django.urls import path
from . import views
app_name="Airline"
urlpatterns=[path("",views.index,name="index"),
            path("<int:flightId>",views.flight,name="flight"),
            path("<int:fid>/book",views.book,name="book")
]

djangoProject1/infiniteScroll/urls.py
from .import views
from django.urls import path

urlpatterns=[path('',views.index,name="index"),
            path('/posts',views.posts,name="posts")
]

djangoProject1/scroll/urls.py
from django.urls import path
from . import views

urlpatterns=[path('',views.index,name="index")

]

djangoProject1/singlePage1/urls.py
from django.urls import path
from . import views

urlpatterns=[path('',views.index,name="index"),
            path('section/<int:num>',views.section,name="section")
]

djangoProject1/singlePageApplication/urls.py
from django.urls import path
from . import views
app_name="singlePage"
urlpatterns=[path("",views.index,name="index")]

djangoProject1/animation/models.py
from django.db import models

# Create your models here.

djangoProject1/flight/models.py
from django.db import models

# Create your models here.

class Airports(models.Model):
    code=models.CharField(max_length=3)
    city=models.CharField(max_length=50)

    def __str__(self):
        return f"{self.code}:{self.city}"
class Flight(models.Model):
    origin=models.ForeignKey(Airports,on_delete=models.CASCADE,related_name="departures")
    destination=models.ForeignKey(Airports,on_delete=models.CASCADE,related_name="arrivals")
    duration=models.IntegerField()

    def __str__(self):
        return f"{self.id}:from {self.origin} to {self.destination} in {self.duration} minutes "

class Passengers(models.Model):
    name=models.CharField(max_length=30)
    flights=models.ManyToManyField(Flight,blank=True,related_name="passengers")

djangoProject1/infiniteScroll/models.py
from django.db import models

# Create your models here.

djangoProject1/scroll/models.py
from django.db import models

# Create your models here.

djangoProject1/singlePage1/models.py
from django.db import models

# Create your models here.

djangoProject1/singlePageApplication/models.py
from django.db import models

# Create your models here.

djangoProject1/animation/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"animation/index.html")

djangoProject1/flight/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


from flight.models import Flight,Passengers
# Create your views here.



def index(request):
    return render(request,"flight/index.html",{"flights":Flight.objects.all()})

def flight(request,flightId):
    f=Flight.objects.get(pk=flightId)

    return render(request,"flight/flight.html",
                  {"flight":f,"passengers":f.passengers.all(),
                  "non_Passengers":Passengers.objects.exclude(flights=f).all()})
def book(request,fid):
    if request.method=="POST":
        flight=Flight.objects.get(pk=fid)
        passenger=Passengers.objects.get(pk=int(request.POST["passenger"]))
        flight.passengers.add(passenger)
        return HttpResponseRedirect(reverse("Airline:flight",args=(fid,)))

djangoProject1/infiniteScroll/views.py
import  time
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.
def index(request):
    return render(request,"infiniteScroll/index.html")
def posts(request):
    start=int(request.GET.get('start') or 1)
    end =int(request.GET.get('end') or start+9)
    data=[]
    for i in range(start,end+1):
        data.append(f'post#{i}')

    time.sleep(1)
    return JsonResponse(
        {"posts":data}
    )

djangoProject1/scroll/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"scroll/index.html")

djangoProject1/singlePage1/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"singlePage1/index.html")
def section(request,num):
    text=["Section1","Section2","Section3"]
    return HttpResponse(text[num-1])

djangoProject1/singlePageApplication/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"singlePage/index.html")

djangoProject1/animation/templates/animation/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>animation</title>
<style>
    @keyframes move{
        0%{
            left: 0%;

        }
        50%{
            left:50%;
            font-size: 100px;
        }
        100%{
            left:0%;
            font-size: 50px;

        }

    }

    h2{
        position: relative;
        animation-name:move;
        animation-duration:3s;
        animation-fill-mode:forwards;
        animation-iteration-count: infinite;
        animation-play-state: paused;
    }

</style>
    <script>
        document.addEventListener('DOMContentLoaded',function(){
            const element=document.querySelector('h2');
            document.querySelector('button').onclick=()=>{

                if(element.style.animationPlayState==='paused'){
                   element.style.animationPlayState='running';
                }else{
                    element.style.animationPlayState='paused';
                }
            }
        });
    </script>
</head>
<body>
<button>Animate</button>
<h2>Welcome</h2>
</body>
</html>

djangoProject1/flight/templates/flight/flight.html
{% extends 'flight/layout.html' %}
{% block body %}
<h1>Flight:{{ flight.id }}</h1>
<ul>
<li>{{ flight.origin }} to {{ flight.destination }}</li>
</ul>
<h1>Passengers</h1>
    <ul>
    {% for passenger in passengers %}
        <li>{{ passenger.name }}</li>
        {% empty %}
        <li>No Passengers</li>
    {% endfor %}
    </ul>
    <h1>Add Passengers to this flight</h1>
    <form action="{% url 'Airline:book' flight.id  %}" method="post">
    {% csrf_token %}
    <select name="passenger">
        {% for passenger in non_Passengers %}
        <option value="{{ passenger.id }}">{{ passenger.name}}</option>
        {% endfor %}
    </select>
    <input type="submit">
    </form>
    <a href="{% url 'Airline:index' %}">Flight List</a>
{% endblock %}

djangoProject1/flight/templates/flight/index.html
{% extends  'flight/layout.html' %}
{% block body %}
<ul>
{% for flight in flights %}
    <li>
        <a href="{% url "Airline:flight" flight.id %}">
            Flight:{{ flight.id }} From {{ flight.origin }} to {{ flight.destination }} in {{ flight.duration }} minutes
        </a>
    </li>
{% endfor %}
</ul>
{% endblock %}

djangoProject1/flight/templates/flight/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Airline</title>
</head>
<body>
{% block  body %}

{% endblock %}
</body>
</html>

djangoProject1/infiniteScroll/templates/infiniteScroll/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Infinite Scrolling</title>
    <style>
        @keyframes hide {
        0%{
            opacity: 1;
            height: 100%;
            line-height: 100%;
            padding: 20px;
            margin-bottom: 20px;

        }
            75%{
                opacity: 0;
                height: 100%;
                line-height: 100%;
                padding: 20px;
                margin-bottom: 20px;


            }
            100%{
                opacity: 0;
                height: 0%;
                line-height: 0%;
                padding: 0px;
                margin-bottom: 0px;

            }
        }
        .post{
            background-color:greenyellow;
            font-size: 25px;
            padding: 20px;
            margin:20px;
            font-family: sans-serif;
            animation-name: hide;
            animation-play-state: paused;
            animation-fill-mode: forwards;
            animation-duration: 2s;
        }
        button{
            float: right;
            height: 30px;
            width:50px;
        }
    </style>
    <script>
        let counter=1;
        const quantity=20;
        document.addEventListener('DOMContentLoaded',load);
        function  load(){
            const start=counter;
            const end=start+quantity-1;
            counter=end+1;
            fetch(`infiniteScroll/posts?start=${start}&end=${end}`)
            .then(response=>response.json())
            .then(data=>{
                data.posts.forEach(add_post);
            })

        }
        function add_post(content){
          const post=document.createElement('div');
          post.className="post";
          post.innerHTML=(`${content} <button class="hide">hide</button>`);
          document.querySelector("#posts").append(post);
        }
        window.onscroll=()=>{
            if(window.innerHeight+window.scrollY>=document.body.offsetHeight){
                load();
            }
        };
        document.addEventListener('click',event=>{
            const element=event.target;
            if(element.className==='hide'){

                element.parentElement.style.animationPlayState='running';
                element.parentElement.addEventListener('animationend',()=>{
                    element.parentElement.remove();
                })

            }
        });
    </script>

</head>
<body>
<div id="posts">

</div>
</body>
</html>

djangoProject1/singlePage1/templates/singlePage1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script>
        function showSection(num){
            fetch(`section/${num}`)
            .then(response=>response.text())
            .then(text=>{
                console.log(text);
               document.querySelector('#content').innerHTML=text;
            });
        }
        document.addEventListener('DOMContentLoaded',()=>{
            document.querySelectorAll('button').forEach(b=>{
                b.addEventListener('click',function(){
                    const section=this.dataset.section;
                    //pushing section details to the history in order to maintain URL
                    history.pushState({section:section},"",`section${section}`);
                    showSection(this.dataset.section);

                });
            });
        });

        window.onpopstate=function(event){
            console.log(event.state.section);
            showSection(event.state.section);
        }
    </script>
</head>
<body>
    <h1>single Page 1</h1>
    <button data-section="1">section1</button>
    <button data-section="2">section2</button>
    <button data-section="3">section3</button>
    <div id="content">
    </div>
</body>
</html>

djangoProject1/singlePageApplication/templates/singlePage/index.html
{% extends 'singlePage/layout.html' %}


{% block body %}
    <style>

    div{
        display: none;
    }
    </style>
    <script>
    function showPage(page){
        document.querySelectorAll('div').forEach(d=>{
            d.style.display='none';
        });
        document.querySelector(`#${page}`).style.display='block';
    }
    document.addEventListener('DOMContentLoaded',function (){
        document.querySelectorAll('button').forEach(button=>{
            button.onclick=function(){
                showPage(this.dataset.page);
            }

        });
    });
    </script>
    <h1>Single Page Application</h1>
    <button data-page="page1">Page1</button>
    <button data-page="page2">Page2</button>
    <button data-page="page3">Page3</button>
    <div id="page1">
        <h1>Page1</h1>
    </div>
    <div id="page2">
        <h1>Page2</h1>
    </div>
    <div id="page3">
        <h1>Page3</h1>
    </div>
{% endblock %}

djangoProject1/singlePageApplication/templates/singlePage/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SinglePage</title>
</head>
<body>

{% block body %}
{% endblock %}
</body>
</html>